# English -> Tamil labels for the book's diagrams (exact-string matches).
TA = {
 'Hypothesis': 'கருதுகோள்', 'Measurement': 'அளவீடு', 'Intervention': 'தலையீடு', 'Response': 'விளைவு',
 'Interpretation': 'விளக்கம்', 'Revised\nprescription': 'திருத்திய\nபயிற்சித் திட்டம்', 'THE AKURA\nRESEARCH CHAIN': 'AKURA\nஆய்வுச் சங்கிலி',
 'Race\nperformance': 'பந்தயச்\nசெயல்திறன்', 'Oxygen\ndelivery': 'ஆக்சிஜன்\nவழங்கல்', 'Running\neconomy': 'ஓட்டச்\nசிக்கனம்',
 'Lactate\nkinetics': 'Lactate\nஇயக்கம்', 'Fuel use': 'எரிபொருள்\nபயன்பாடு', 'Body\ncomposition': 'உடல்\nஅமைப்பு',
 'Training\nhistory': 'பயிற்சி\nவரலாறு', 'Recovery': 'மீட்சி', 'Psychology': 'உளவியல்', 'Environment': 'சூழல்',
 'Social\nfactors': 'சமூகக்\nகாரணிகள்',
 'Air': 'காற்று', 'O₂ at 20.9%': 'O₂ 20.9%', 'Lungs': 'நுரையீரல்', 'ventilation &\ngas exchange': 'சுவாசம் &\nவாயுப் பரிமாற்றம்',
 'Blood': 'இரத்தம்', 'haemoglobin\ncarries O₂': 'ஹீமோகுளோபின்\nO₂ சுமக்கிறது', 'Heart': 'இதயம்', 'cardiac output\n= HR × SV': 'இதய வெளியீடு\n= HR × SV',
 'Muscle': 'தசை', 'capillaries\ndeliver O₂': 'நுண்குழாய்கள்\nO₂ தருகின்றன', 'Mito-\nchondria': 'மைட்டோ-\nகாண்ட்ரியா', 'aerobic ATP': 'ஏரோபிக் ATP',
 'Movement': 'இயக்கம்', 'economy turns\nenergy into speed': 'சிக்கனம் ஆற்றலை\nவேகமாக மாற்றும்',
 'Heart rate (beats/min)': 'இதயத் துடிப்பு (துடிப்பு/நிமிடம்)', 'Stroke volume (mL/beat)': 'Stroke volume (mL/துடிப்பு)',
 'Same pace, similar cardiac output (~17.6 L/min), different heart rates': 'ஒரே வேகம், ஒத்த இதய வெளியீடு (~17.6 L/நிமி), வேறுபட்ட இதயத் துடிப்பு',
 'Athlete X': 'வீரர் X', 'Athlete Y': 'வீரர் Y',
 'Baseline': 'தொடக்க நிலை', 'Hb conc: normal': 'Hb செறிவு: இயல்பு', 'Plasma expansion\n(e.g. heat)': 'பிளாஸ்மா பெருக்கம்\n(எ.கா. வெப்பம்)',
 'Hb conc: ↓ LOWER\nHb mass: unchanged': 'Hb செறிவு: ↓ குறைவு\nHb நிறை: மாற்றமில்லை', 'Red-cell increase\n(e.g. altitude)': 'சிவப்பணு அதிகரிப்பு\n(எ.கா. உயரம்)',
 'Hb conc: ↑ higher\nHb mass: ↑ HIGHER': 'Hb செறிவு: ↑ அதிகம்\nHb நிறை: ↑ அதிகம்', 'Dehydration': 'நீரிழப்பு',
 'Hb conc: ↑ HIGHER\nHb mass: unchanged': 'Hb செறிவு: ↑ அதிகம்\nHb நிறை: மாற்றமில்லை', 'red cells': 'சிவப்பணுக்கள்', 'plasma': 'பிளாஸ்மா',
 "A's VO₂max 60": 'A-இன் VO₂max 60', "B's VO₂max 58": 'B-இன் VO₂max 58', 'race pace\n15 km/h': 'பந்தய வேகம்\n15 km/h',
 'Running speed (km/h)': 'ஓட்ட வேகம் (km/h)', 'Oxygen cost (mL/kg/min)': 'ஆக்சிஜன் செலவு (mL/kg/நிமி)',
 'Runner A: less economical': 'ஓட்டக்காரர் A: குறைந்த சிக்கனம்', 'Runner B: more economical': 'ஓட்டக்காரர் B: அதிக சிக்கனம்',
 'Lower oxygen cost at the same speed = more reserve': 'ஒரே வேகத்தில் குறைந்த ஆக்சிஜன் செலவு = அதிக இருப்பு',
 'Steady\n(aerobic)': 'நிலையான\n(ஏரோபிக்)', 'Threshold\nzone': 'த்ரெஷோல்ட்\nமண்டலம்', 'Severe': 'கடுமை',
 'Blood lactate (mmol/L)': 'இரத்த lactate (mmol/L)', 'A typical lactate–speed curve (illustrative)': 'வழக்கமான lactate–வேக வளைவு (எடுத்துக்காட்டு)',
 'typical marathon\nintensity range': 'வழக்கமான மாரத்தான்\nதீவிர வரம்பு', 'Exercise intensity (% of VO₂max)': 'உடற்பயிற்சி தீவிரம் (VO₂max %)',
 'Share of energy (%)': 'ஆற்றல் பங்கு (%)', 'Fat': 'கொழுப்பு', 'Carbohydrate': 'கார்போஹைட்ரேட்',
 'Fuel mix shifts towards carbohydrate as intensity rises (schematic)': 'தீவிரம் உயர உயர எரிபொருள் கார்போஹைட்ரேட் பக்கம் சாய்கிறது (மாதிரி)',
 'Minutes at the same steady pace': 'ஒரே நிலையான வேகத்தில் நிமிடங்கள்', 'Cool morning (~22 °C)': 'குளிர்ந்த காலை (~22 °C)',
 'Humid Chennai evening (~32 °C, high humidity)': 'ஈரப்பதமான சென்னை மாலை (~32 °C, அதிக ஈரப்பதம்)',
 'Same pace, different day: heat raises and drifts heart rate (illustrative)': 'ஒரே வேகம், வேறு நாள்: வெப்பம் இதயத் துடிப்பை உயர்த்துகிறது (எடுத்துக்காட்டு)',
 'Heart rate at fixed workload falls': 'நிலையான சுமையில் இதயத் துடிப்பு குறைகிறது', 'Plasma volume expands': 'பிளாஸ்மா அளவு பெருகுகிறது',
 'Core temperature response improves': 'உடல் மைய வெப்ப எதிர்வினை மேம்படுகிறது', 'Sweating earlier / more effective': 'முன்கூட்டிய / சிறந்த வியர்வை',
 'Exercise capacity in heat improves': 'வெப்பத்தில் உடற்பயிற்சித் திறன் உயர்கிறது', 'Days of repeated heat exposure (approximate)': 'தொடர் வெப்ப வெளிப்பாட்டு நாட்கள் (தோராயமாக)',
 'Heat acclimation: the usual order of adaptations (approximate)': 'வெப்பப் பழக்கப்படுத்தல்: தகவமைப்புகளின் வழக்கமான வரிசை (தோராயமாக)',
 'Chennai\n~7 m · 149 mmHg': 'சென்னை\n~7 m · 149 mmHg', 'Bengaluru\n~920 m · 133 mmHg': 'பெங்களூரு\n~920 m · 133 mmHg',
 'Kodaikanal\n~2130 m · 113 mmHg': 'கொடைக்கானல்\n~2130 m · 113 mmHg', 'Ooty\n~2240 m · 111 mmHg': 'ஊட்டி\n~2240 m · 111 mmHg',
 'Elevation (m)': 'உயரம் (m)', 'Inspired PO₂ (mmHg)': 'உள்ளிழுக்கும் PO₂ (mmHg)',
 'Oxygen fraction stays ~20.9%, but the pressure of oxygen falls': 'ஆக்சிஜன் சதவீதம் ~20.9% தான்; ஆனால் ஆக்சிஜன் அழுத்தம் குறைகிறது',
 '20.9%\nO₂': '20.9%\nO₂', 'Sea level (Chennai)\n≈ 760 mmHg total pressure': 'கடல் மட்டம் (சென்னை)\n≈ 760 mmHg மொத்த அழுத்தம்',
 '~2,200 m (Ooty)\n≈ 580 mmHg total pressure': '~2,200 m (ஊட்டி)\n≈ 580 mmHg மொத்த அழுத்தம்', 'Same percentage, fewer molecules per breath': 'அதே சதவீதம், ஒவ்வொரு மூச்சிலும் குறைந்த மூலக்கூறுகள்',
 'LIVE HIGH  ~2,200 m\nsleep & rest in hypoxia': 'உயரத்தில் வாழ்  ~2,200 m\nhypoxia-வில் தூக்கம், ஓய்வு', 'TRAIN LOW\nquality sessions': 'தாழ்வில் பயிற்சி\nதரமான அமர்வுகள்',
 'descend\nto train': 'இறங்கிப்\nபயிற்சி', 'Aim: red-cell adaptation\nwithout losing\ntraining quality': 'நோக்கம்: பயிற்சித் தரம்\nகுறையாமல்\nசிவப்பணு தகவமைப்பு',
 'HEAT': 'வெப்பம்', 'ALTITUDE': 'உயரம்', 'Plasma volume ↑\nSweating earlier\nLower core temp\nThermal comfort': 'பிளாஸ்மா அளவு ↑\nமுன்கூட்டிய வியர்வை\nகுறைந்த மைய வெப்பம்\nவெப்ப வசதி',
 'EPO signalling ↑\nRed-cell mass ↑\n(with iron, time)\nVentilatory change': 'EPO சமிக்ஞை ↑\nசிவப்பணு நிறை ↑\n(இரும்பு, காலத்துடன்)\nசுவாச மாற்றம்',
 'Cardiovascular\nstress\nHR at fixed\nworkload\nNeed for\nrecovery': 'இதய-இரத்த\nஅழுத்தம்\nநிலையான சுமையில்\nHR\nமீட்சித்\nதேவை',
 'The last 10 km': 'கடைசி 10 km', 'Distance (km)': 'தூரம் (km)', 'Pace (min/km, decimal)': 'வேகம் (நிமி/km, தசம)', 'Even pacing': 'சீரான வேகம்',
 'Fast start, late fade': 'வேகத் தொடக்கம், தாமதத் தளர்வு', 'Many marathons are lost in the first half (illustrative)': 'பல மாரத்தான்கள் முதல் பாதியிலேயே இழக்கப்படுகின்றன (எடுத்துக்காட்டு)',
 'Half': 'அரை', 'Marathon': 'மாரத்தான்', 'Relative performance index': 'ஒப்பீட்டுச் செயல்திறன் குறியீடு',
 'Athlete A: speed-dominant': 'வீரர் A: வேகம் மேலோங்கியவர்', 'Athlete B: durable': 'வீரர் B: நீடித்திறன் மிக்கவர்', 'Distance-specific expression (illustrative)': 'தூரம் சார்ந்த வெளிப்பாடு (எடுத்துக்காட்டு)',
 'AEI-FITNESS\nWhat can the athlete do?': 'AEI-FITNESS\nவீரர் என்ன செய்ய முடியும்?', 'AEI-READINESS\nHow ready are they today?': 'AEI-READINESS\nஇன்று எவ்வளவு தயார்?',
 'race results · threshold · economy\nVO₂ tests · durability': 'பந்தய முடிவுகள் · threshold · சிக்கனம்\nVO₂ சோதனைகள் · நீடித்திறன்',
 'sleep · HRV trend · resting HR\nfatigue · load · heat': 'தூக்கம் · HRV போக்கு · ஓய்வு HR\nசோர்வு · சுமை · வெப்பம்',
 'Training\nprescription': 'பயிற்சித்\nதிட்டம்', 'Session done +\nnew data': 'அமர்வு முடிந்தது +\nபுதிய தரவு', 'updates AEI': 'AEI-ஐப் புதுப்பிக்கிறது',
 'P Performance': 'P செயல்திறன்', 'A Aerobic': 'A ஏரோபிக்', 'T Threshold': 'T த்ரெஷோல்ட்', 'E Economy': 'E சிக்கனம்', 'O Oxygen': 'O ஆக்சிஜன்',
 'C Cardio': 'C இதயம்', 'R Recovery': 'R மீட்சி', 'H Heat': 'H வெப்பம்', 'X Altitude': 'X உயரம்', 'D Durability': 'D நீடித்திறன்',
 'Athlete A': 'வீரர் A', 'Athlete B': 'வீரர் B', 'illness': 'நோய்', 'heat block': 'வெப்பத் தொகுதி', 'Day': 'நாள்', 'Index value': 'குறியீட்டு மதிப்பு',
 'Daily value': 'தினசரி மதிப்பு', '7-day': '7-நாள்', '28-day': '28-நாள்', 'Trends with annotations tell the story (illustrative)': 'குறிப்புகளுடன் போக்குகள் கதை சொல்கின்றன (எடுத்துக்காட்டு)',
 'Lower risk': 'குறைந்த ஆபத்து', 'Caution': 'எச்சரிக்கை', 'High risk:\nmodify session': 'அதிக ஆபத்து:\nஅமர்வை மாற்று', 'Very high:\nconsider cancelling': 'மிக அதிகம்:\nரத்து செய்வதைப் பரிசீலி',
 'Example WBGT risk bands: follow local sports-medicine guidance': 'எடுத்துக்காட்டு WBGT ஆபத்து வரம்புகள்: உள்ளூர் விளையாட்டு மருத்துவ வழிகாட்டலைப் பின்பற்றவும்',
 'Heart rate (bpm)': 'இதயத் துடிப்பு (bpm)', 'Speed (km/h)': 'வேகம் (km/h)', '1st half: speed/HR ratio': 'முதல் பாதி: வேகம்/HR விகிதம்',
 '2nd half: ratio falls': 'இரண்டாம் பாதி: விகிதம் குறைகிறது', 'Minutes': 'நிமிடங்கள்',
 'Pace–HR decoupling: speed holds while heart rate drifts up': 'பேஸ்–HR விலகல் (decoupling): வேகம் நிலைக்கிறது, இதயத் துடிப்பு ஏறுகிறது',
 'Speed': 'வேகம்', 'sprints, strides': 'ஸ்பிரிண்ட், ஸ்ட்ரைட்ஸ்', 'Power': 'சக்தி', 'VO₂max intervals': 'VO₂max இடைவெளிகள்', 'Threshold': 'த்ரெஷோல்ட்',
 'controlled-hard': 'கட்டுப்பாடான-கடினம்', 'Endurance': 'சகிப்பு', 'long runs, steady': 'நீண்ட ஓட்டம், நிலையானது', 'Aerobic': 'ஏரோபிக்', 'easy volume': 'எளிய அளவு',
 'very easy, restorative': 'மிக எளிது, மீட்பு', 'harder,\nless volume': 'கடினம்,\nகுறைந்த அளவு', 'easier,\nmost volume': 'எளிது,\nஅதிக அளவு',
 'Mon': 'திங்', 'Tue': 'செவ்', 'Wed': 'புத', 'Aerobic +\nstrength': 'ஏரோபிக் +\nவலிமை', 'Thu': 'வியா', 'Fri': 'வெள்', 'Sat': 'சனி', 'Long run': 'நீண்ட\nஓட்டம்',
 'Sun': 'ஞாயி', 'Reset': 'மீட்டமைப்பு', 'An illustrative 3–3–1 week (individualise every element)': 'எடுத்துக்காட்டு 3–3–1 வாரம் (ஒவ்வொன்றையும் தனிப்பயனாக்கவும்)',
 'LIMITED\nCONFIDENCE': 'குறைந்த\nநம்பகத்தன்மை', 'old race · missing HR\nno recent tests': 'பழைய பந்தயம் · HR இல்லை\nசமீப சோதனை இல்லை',
 'MODERATE\nCONFIDENCE': 'மிதமான\nநம்பகத்தன்மை', 'recent race · partial\nrecovery data': 'சமீப பந்தயம் · பகுதி\nமீட்சித் தரவு',
 'HIGH\nCONFIDENCE': 'உயர்\nநம்பகத்தன்மை', 'recent race · complete HR\nrepeated lab tests': 'சமீப பந்தயம் · முழு HR\nமீண்டும் ஆய்வகச் சோதனைகள்',
 'more complete, recent and standardised data →': 'முழுமையான, சமீபத்திய, தரப்படுத்திய தரவு →',
 'capacity & profile\nchanges over weeks': 'திறன் & சுயவிவரம்\nவாரங்களில் மாறும்', "today's readiness\nchanges daily": 'இன்றைய தயார்நிலை\nதினமும் மாறும்',
 'together → the right session today': 'இணைந்து → இன்றைக்குச் சரியான அமர்வு',
 '1 Intake': '1 சேர்க்கை', '2 Baseline': '2 தொடக்க நிலை', '3 AEI profile': '3 AEI சுயவிவரம்', '4 Prescription': '4 பயிற்சித் திட்டம்', '5 Execution': '5 செயல்படுத்தல்',
 '6 Environment\n& recovery': '6 சூழல்\n& மீட்சி', '7 Readiness': '7 தயார்நிலை', '8 Adaptation\ndecision': '8 தகவமைப்பு\nமுடிவு', '9 Retest': '9 மறுசோதனை',
 '10 AEI update': '10 AEI புதுப்பிப்பு', 'CLOSED-LOOP\nCOACHING': 'மூடிய-சுழற்சி\nபயிற்சி',
 'What can the\nathlete do?': 'வீரர் என்ன\nசெய்ய முடியும்?', 'Fitness 78\n▲ 28-day': 'உடற்தகுதி 78\n▲ 28-நாள்', 'How ready are\nthey today?': 'இன்று எவ்வளவு\nதயார்?',
 'Ready: modify\nsession': 'தயார்: அமர்வை\nமாற்று', 'What changed\nrecently?': 'சமீபத்தில் என்ன\nமாறியது?', 'Heat block wk 2\nsleep ↓': 'வெப்பம் வா.2\nதூக்கம் ↓',
 'confidence: moderate  ·  raw data one click away  ·  coach notes': 'நம்பகத்தன்மை: மிதம்  ·  மூலத் தரவு ஒரு கிளிக்கில்  ·  பயிற்சியாளர் குறிப்புகள்',
 'TRAIN': 'பயிற்சி', 'MEASURE': 'அளவிடு', 'UNDERSTAND': 'புரிந்துகொள்', 'ADAPT': 'தகவமை', 'the athlete': 'வீரர்',
 'CHENNAI  ·  SEA LEVEL': 'சென்னை  ·  கடல் மட்டம்', 'OOTY  ·  ~2,240 m': 'ஊட்டி  ·  ~2,240 m',
 'Pace (min/km)  —  faster to the right': 'வேகம் (நிமி/km)  —  வலப்புறம் வேகமானது', 'AKURA training paces for a 22:00 5K runner': '22:00 5K ஓட்டக்காரருக்கான AKURA பயிற்சி வேகங்கள்',
 'chart pace': 'அட்டவணை வேகம்', 'consider\nmoving indoors': 'உள்ளரங்குக்கு\nமாற்றலாம்', 'Below 18': '18-க்குக் கீழ்', 'Above 28': '28-க்கு மேல்',
 'Easy pace at same effort (min/km)': 'அதே முயற்சியில் எளிய வேகம் (நிமி/km)',
 'Same effort, slower pace: an easy 6:00/km runner in rising heat (illustrative)': 'அதே முயற்சி, மெதுவான வேகம்: உயரும் வெப்பத்தில் 6:00/km ஓட்டக்காரர் (எடுத்துக்காட்டு)',
 'Foundation': 'அடித்தளம்', 'Aerobic build': 'ஏரோபிக் வளர்ச்சி', 'Specific strength': 'குறிப்பிட்ட வலிமை', 'Race-\nspecific': 'பந்தயச்\nசிறப்பு', 'Taper': 'டேப்பர்',
 'heat block\n(warm race)': 'வெப்பத் தொகுதி\n(வெப்பப் பந்தயம்)', 'baseline': 'தொடக்கம்', '5K TT': '5K சோதனை', 'threshold\ntest': 'threshold\nசோதனை',
 'half\nmarathon': 'அரை\nமாரத்தான்', 'RACE': 'பந்தயம்', 'long run (km, dashed): builds with lighter weeks': 'நீண்ட ஓட்டம் (km, கோடு): இலகு வாரங்களுடன் வளர்கிறது',
 'Phases': 'கட்டங்கள்', 'Tests': 'சோதனைகள்', 'Week': 'வாரம்', 'The AKURA 24-week marathon roadmap': 'AKURA 24-வார மாரத்தான் வழிவரைபடம்',
 '1 Foundation': '1 அடித்தளம்', 'enjoy & learn': 'மகிழ்ந்து கற்றல்', '2 Aerobic\ndevelopment': '2 ஏரோபிக்\nவளர்ச்சி', 'consistency': 'தொடர்ச்சி',
 '3 Structured\ntraining': '3 கட்டமைந்த\nபயிற்சி', 'AEI begins': 'AEI தொடக்கம்', '4 Performance': '4 செயல்திறன்', 'lab + clinician': 'ஆய்வகம் + மருத்துவர்',
 '5 High\nperformance': '5 உயர்\nசெயல்திறன்', 'full AEI team': 'முழு AEI குழு',
 'years of consistent training · load and measurement grow together': 'ஆண்டுகள் தொடர் பயிற்சி · சுமையும் அளவீடும் சேர்ந்து வளர்கின்றன',
 'PHASE 1': 'கட்டம் 1', 'PHASE 2': 'கட்டம் 2', 'PHASE 3': 'கட்டம் 3', 'PHASE 4': 'கட்டம் 4', 'PHASE 5': 'கட்டம் 5',
 'Data\nfoundation': 'தரவு\nஅடித்தளம்', 'Reliability': 'நம்பகத்தன்மை', 'Model\nbuilding': 'மாதிரி\nஉருவாக்கம்', 'Prospective\nvalidation': 'முன்னோக்குச்\nசரிபார்ப்பு',
 'External\nvalidation': 'வெளிச்\nசரிபார்ப்பு', 'AEI v0.1 (this book)': 'AEI v0.1 (இந்நூல்)',
 'Indian national records over time (faster is higher)': 'இந்திய தேசியச் சாதனைகள் காலப்போக்கில் (மேலே = வேகமானது)',
 'Indian national record slower than world record (%)': 'உலகச் சாதனையைவிட இந்தியச் சாதனை மெதுவான அளவு (%)',
 'How far from the world? Gap between Indian and world records': 'உலகிலிருந்து எவ்வளவு தூரம்? இந்திய–உலகச் சாதனை இடைவெளி',
 'Number of elite athletes profiled in this book': 'இந்நூலில் விவரிக்கப்பட்ட உயர்நிலை வீரர்களின் எண்ணிக்கை',
 'Pathways into Indian elite distance running': 'இந்திய உயர்நிலை நீண்டதூர ஓட்டத்துக்கான பாதைகள்',
}

# Chart labels for Part XVIII figures (translated alongside the chapter text)
import json as _json, os as _os
_p = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "tdelta", "chart_labels.json")
if _os.path.exists(_p):
    TA.update({k: v for k, v in _json.load(open(_p, encoding="utf8")).items() if v})
