# Generates content/09_part17_toolkit.md: AKURA pace charts and roadmaps (Part XVII).
import os

E = 1.06  # Riegel fatigue exponent


def fmt(s):
    s = round(s); h, r = divmod(s, 3600); m, sec = divmod(r, 60)
    return f"{h}:{m:02d}:{sec:02d}" if h else f"{m}:{sec:02d}"


def model(T5):
    race = lambda d: T5 * (d / 5000) ** E
    def pace_for(t):  # pace (s/km) of an all-out effort lasting t seconds
        d = 5000 * (t / T5) ** (1 / E); return t / d * 1000
    T = pace_for(3600)
    return {
        "5K": T5, "10K": race(10000), "HM": race(21097.5), "M": race(42195),
        "T": T, "M_p": race(42195) / 42.195, "P": pace_for(660), "S400": pace_for(300) * 0.4,
        "Rec": T / 0.70, "A": (T / 0.80, T / 0.70), "En": (T / 0.88, T / 0.80),
    }


rows5k = list(range(15 * 60, 30 * 60 + 1, 60)) + list(range(32 * 60, 40 * 60 + 1, 120))

L = []
w = L.append
w("PART XVII — THE AKURA TOOLKIT")
w("")
w("PARTINTRO: This final Part turns the ideas of the book into tools a coach can use on Monday morning. It gives AKURA pace and race-equivalence charts, explains how to adjust them for Chennai heat and hill-station altitude, and sets out three roadmaps: a 24-week marathon roadmap, a long-term athlete development roadmap, and the research roadmap that will take the AKURA Endurance Index from prototype to validated tool. Every chart is a starting point, to be checked against the athlete's own heart rate, effort and response.")
w("")

# ---------------- Chapter 85 ----------------
w("## 85. The AKURA Pace Charts")
w("")
w("Every coach eventually needs a simple table: \"My athlete just ran this race. What paces should they train at?\" Pace charts such as Jack Daniels' VDOT tables have helped a generation of runners answer that question. AKURA's charts serve the same practical purpose, but they are built from a transparent, openly stated model so that any coach can check the arithmetic, and they are designed to be adjusted by the environment and readiness layers described in earlier chapters.")
w("")
w("### How the charts are calculated")
w("")
w("The charts start from one recent, honest race result, ideally a 5K run on a flat course in cool conditions. From that anchor, equivalent performances at other distances are estimated with Riegel's well-known endurance formula: predicted time = known time × (new distance ÷ known distance) raised to the power 1.06. The same relationship is used to estimate the pace an athlete could hold for a given duration, which gives the training paces.")
w("")
w("- **Threshold pace** is the estimated pace the athlete could race for about 60 minutes. It should feel controlled-hard.")
w("- **Power pace** is the estimated pace for an all-out effort of about 11 minutes, used for VO₂max-type intervals of 2–5 minutes.")
w("- **Speed** is given as a 400 m repetition time, based on the pace for an all-out effort of about 5 minutes, used with full recovery.")
w("- **Marathon pace** is the Riegel marathon prediction divided by 42.195 km.")
w("- **Recovery, Aerobic and Endurance** paces are set as percentages of threshold speed: Recovery slower than 70%, Aerobic 70–80%, and Endurance 80–88%.")
w("")
w("KEY: AKURA pace charts turn one recent race into a full set of training paces using a published, transparent formula. They are a starting point: heart rate, effort, heat and readiness decide the final pace on the day.")
w("")
w("### Chart 1: Equivalent race performances")
w("")
w("Find the athlete's current 5K time in the first column. The other columns show what the model predicts at longer distances for a runner whose endurance is well developed for that distance.")
w("")
w("|5K|10K|Half marathon|Marathon|")
for T5 in rows5k:
    m = model(T5); w(f"|{fmt(m['5K'])}|{fmt(m['10K'])}|{fmt(m['HM'])}|{fmt(m['M'])}|")
w("")
w("The marathon column assumes marathon-specific training: regular long runs and enough weekly volume. Runners on lower mileage, beginners and athletes racing in heat usually run slower than predicted, often by 5–10% or more. This gap is exactly what AKURA calls the durability gap, described in Chapter 36; the difference between an athlete's 5K prediction and actual marathon result is useful data, not a failure.")
w("")
w("### Chart 2: AKURA training paces (min/km)")
w("")
w("|5K|Recovery (slower than)|Aerobic|Endurance|Marathon|Threshold|Power|Speed 400 m|")
for T5 in rows5k:
    m = model(T5)
    w(f"|{fmt(T5)}|{fmt(m['Rec'])}|{fmt(m['A'][0])}–{fmt(m['A'][1])}|{fmt(m['En'][0])}–{fmt(m['En'][1])}|{fmt(m['M_p'])}|{fmt(m['T'])}|{fmt(m['P'])}|{fmt(m['S400'])}|")
w("")
w("COACH: Use the chart to set the first week of training, then let the athlete's response correct it. If heart rate at \"Aerobic\" pace drifts well above the athlete's usual easy range, or the threshold session feels like a race, the chart is too fast for this athlete today. Re-anchor the chart after every honest race or time trial, roughly every 6–8 weeks.")
w("")
w("### Using the charts safely")
w("")
w("A chart is only as good as its anchor. An old race, a downhill course, a race run on a cool December morning or a time trial run while unwell will all give misleading paces. Where the athlete has no recent race, use a 5K time trial on a flat measured course, run early in the morning, after two easy days.")
w("")
w("The easy paces are deliberately wide. On hot days, after poor sleep or in the first days at altitude, athletes should run towards the slow end of the range or slower. Easy running is defined by effort and heart rate first; the pace column is a guide, not a target.")
w("")
w("FIELD: Setting an athlete's paces ; Run a 5K time trial on a flat, measured course in the coolest part of the day ; Record time, temperature, humidity and average heart rate ; Find the nearest 5K time in Chart 2 and write the paces into the athlete's AEI card ; For the first two weeks, check heart rate and RPE in every session against the prescribed domain ; Adjust the paces for heat and altitude using Chapter 86 ; Retest after 6–8 weeks or after a race")
w("")
w("FIG: f29_pace_zones.png | Example AKURA training paces for an athlete with a 22:00 5K. Easy domains are deliberately wide; the harder domains are narrow and used in smaller doses.")
w("")
w("MYTH: Faster training paces make faster racers. || Training much faster than the chart usually adds fatigue without adding adaptation. Most improvement comes from consistent Aerobic and Endurance work plus well-judged Threshold sessions.")
w("")
w("CHECK: Take one of your athletes. What 5K time would you use as their anchor, how recent is it, and in what conditions was it run? How confident are you in the paces it produces?")
w("")

# ---------------- Chapter 86 ----------------
w("## 86. Adjusting Paces for Heat and Altitude")
w("")
w("A pace chart assumes a cool, still, sea-level day. Chennai in May is not that day, and neither is the first week in Ooty. This chapter gives AKURA's working adjustments. They are practical coaching guidance drawn from the physiology in Parts III and IV, not validated equations, and they are always overruled by heart rate, perceived effort and warning signs.")
w("")
w("### Heat and humidity")
w("")
w("Marathon results slow progressively as environmental heat stress rises, and slower runners, who are exposed for longer, tend to be affected more. In humid heat, sweat evaporates poorly, so heart rate climbs at the same pace. The practical response is to hold effort, not pace.")
w("")
w("|WBGT (°C)|Easy and endurance runs|Threshold and interval sessions|Races and long runs|")
w("|Below 18|Use chart paces|Use chart paces|Use chart paces|")
w("|18–23|Run by heart rate; often 2–4% slower|Slow by about 2–4%, or shorten reps|Expect a small slowdown; drink to plan|")
w("|23–28|Run by heart rate; often 5–8% slower|Move to cooler hours, cut volume, slow by 5% or more|Reduce goals; heat-acclimated athletes only|")
w("|Above 28|Short, very easy, or move indoors|Postpone|Follow medical and event guidance; consider not racing|")
w("")
w("On a humid Chennai evening, a 5:30/km aerobic run might become 5:45–6:00/km at the same heart rate. That is not lost fitness; it is the price of thermoregulation. The AEI records the environment so that the slower pace is interpreted correctly.")
w("")
w("KEY: In heat, hold the effort and let the pace fall. A heart-rate ceiling and a stop rule protect the athlete better than any pace target.")
w("")
w("### Altitude")
w("")
w("At the moderate altitudes of Ooty and Kodaikanal, oxygen pressure is roughly a quarter lower than at sea level. Easy running feels harder and fast intervals are noticeably slower in the first days.")
w("")
w("|Camp phase|Easy running|Threshold|Power and speed|")
w("|Days 1–4|By effort only; expect clearly slower paces|Avoid|Avoid|")
w("|Days 5–10|By effort; paces begin to return|By effort; typically a few per cent slower than sea-level pace|Short reps with long recovery; do not chase sea-level times|")
w("|Days 11 onwards|Close to normal effort|By heart rate and RPE|Consider descending to lower ground for key fast sessions|")
w("|Return to sea level|Normal|Normal after a few days|Retest before racing|")
w("")
w("COACH: Write two numbers on every hot-weather or altitude session plan: the heart-rate ceiling and the stop rule. For example: \"Easy 50 minutes, heart rate below 150; stop and cool down if dizzy, confused, nauseous or if sweating stops.\" The pace is recorded afterwards, not chased during the run.")
w("")
w("FIG: f30_heat_adjust.png | Illustrative only: how the same easy effort translates into slower paces as WBGT rises. Use the athlete's own heart rate and response to set the real adjustment.")
w("")
w("CHECK: What heart-rate ceiling would you give your athletes for easy runs in May, and what is your stop rule?")
w("")

# ---------------- Chapter 87 ----------------
w("## 87. The 24-Week Marathon Roadmap")
w("")
w("A marathon is built over months, not weeks. The AKURA marathon roadmap divides 24 weeks into five phases, each with a clear purpose, a key session type and a planned retest. The roadmap is a map, not a timetable: each phase ends only when the athlete has absorbed it, and the AEI trend decides whether to move on, repeat or reduce.")
w("")
w("FIG: f31_marathon_roadmap.png | The AKURA 24-week marathon roadmap: five phases, four testing points, a planned heat block for a warm-weather race and a progressive long run.")
w("")
w("### The five phases")
w("")
w("|Weeks|Phase|Main purpose|Key sessions|Test at end|")
w("|1–6|Foundation|Consistency, aerobic volume, strength habit|Aerobic runs, strides, strength twice a week|5K time trial; easy pace at fixed HR|")
w("|7–12|Aerobic build|Raise volume and long-run length|Long run, Endurance runs, one Threshold session|Threshold test; long-run decoupling|")
w("|13–18|Specific strength|Sustain higher fractions of capacity|Threshold, marathon-pace blocks in long runs|Half-marathon or 15K race|")
w("|19–21|Race-specific|Rehearse race pace, fuelling and heat plan|Long runs with marathon-pace finish; heat sessions if race is warm|Final long run review|")
w("|22–24|Taper and race|Arrive fresh, keep sharpness|Reduced volume, short marathon-pace efforts|Race|")
w("")
w("### Progression rules")
w("")
w("- Increase the long run gradually, typically by 2–3 km every one to two weeks, with a lighter week every third or fourth week.")
w("- Add only one new stress at a time: volume, intensity, heat or hills.")
w("- If AEI-Readiness is repeatedly low, or pace-HR decoupling on long runs worsens, hold the current week rather than progressing.")
w("- Practise race-day fuelling in every long run from week 13 onwards.")
w("- For a warm race, schedule a controlled 10–14 day heat-acclimation block in weeks 19–21, as described in Chapter 20, not in the final week.")
w("")
w("KEY: The roadmap moves forward only when the athlete has absorbed the current phase. Testing points turn the plan into a feedback loop.")
w("")
w("COACH: Put the four testing weeks into the calendar on day one and treat them as fixed appointments. The results are what allow you to adjust the plan with confidence rather than guessing.")
w("")
w("### An example: a Chennai club marathoner")
w("")
w("Consider an illustrative athlete with a 25:00 5K preparing for a January marathon in Chennai. Chart 2 suggests Aerobic runs around 6:34–7:30/km, Threshold around 5:15/km and marathon pace around 5:41/km. Because the Foundation and Aerobic phases fall in the monsoon and early winter, most sessions are run early in the morning and by heart rate. The heat block is unnecessary for a cool January start but essential if the athlete is racing a warm event. The half-marathon test in week 18 is used to re-anchor paces for the final phase.")
w("")
w("CHECK: Where would your next target race fall in this roadmap if you started today? Which phase would you have to shorten, and what risk does that create?")
w("")

# ---------------- Chapter 88 ----------------
w("## 88. The Athlete Development Roadmap")
w("")
w("A world-class endurance athlete is built over many years. The AKURA development roadmap describes five stages, from a school or beginner runner to a performance athlete. Each stage has its own training priorities and, just as importantly, its own level of measurement. Measuring too much too early can be as harmful as measuring too little too late.")
w("")
w("FIG: f32_development_roadmap.png | The AKURA athlete development roadmap: five stages in which training load and measurement depth grow together.")
w("")
w("|Stage|Typical athlete|Training priority|Measurement level|")
w("|1 Foundation|School runner or adult beginner|Enjoyment, running skill, all-round athleticism|Race times, simple logs, wellbeing|")
w("|2 Aerobic development|Regular club runner|Consistent aerobic volume, strength basics|Pace-HR, sleep, RPE, 5K tests|")
w("|3 Structured training|Competitive club or college runner|Threshold work, long runs, planned progression|AEI-Fitness and Readiness, heat logging|")
w("|4 Performance|State or national-level athlete|Specific preparation, heat and altitude blocks|Lab tests, blood markers with clinician|")
w("|5 High performance|International-level athlete|Individualised, multidisciplinary support|Full AEI profile with medical team|")
w("")
w("### Moving between stages")
w("")
w("Athletes move up when they can absorb the current stage consistently for months, not when they run one good race. Age matters too: young athletes should build broad athletic ability and enjoyment before specialising in high volume. For adults who start late, the stages still apply, but progress is limited more by tissue tolerance and life load than by physiology.")
w("")
w("KEY: Training load and measurement should grow together. Each stage asks a different question, and the AEI adds detail only when the athlete is ready to use it.")
w("")
w("COACH: Write each athlete's stage on their AEI card. It prevents two common mistakes: giving a beginner a laboratory test battery they do not need, and coaching a national-level athlete with nothing more than a stopwatch.")
w("")
w("CHECK: Which stage is each of your athletes at? What single step would move each of them to the next stage?")
w("")

# ---------------- Chapter 89 ----------------
w("## 89. The AEI Research Roadmap")
w("")
w("The AKURA Endurance Index is presented in this book as Prototype Edition 0.1. The research roadmap sets out how it can become a validated tool. Each phase has a clear output and a clear test, and the index should not be used for high-stakes decisions until the later phases are complete.")
w("")
w("FIG: f33_aei_roadmap.png | The AEI research roadmap, from prototype data schema to externally validated index. Timings are targets and depend on data quality and collaboration.")
w("")
w("|Phase|Goal|Main output|Success test|")
w("|1 Data foundation|Collect clean, consistent data|AEI card, data fields, quality rules|Complete records for a pilot group|")
w("|2 Reliability|Show that measurements repeat|Typical error for each test|Known smallest worthwhile change|")
w("|3 Model building|Learn domain weights from data|First calibrated AEI model|Beats race time alone on held-out data|")
w("|4 Prospective validation|Test predictions in new seasons|Validation report|Good calibration and useful decisions|")
w("|5 External validation|Test in other cities and groups|AEI version 1.0|Works beyond the original group|")
w("")
w("### What will count as success")
w("")
w("The AEI will be judged by the tests set out in Chapter 68. Does it predict outcomes better than race performance alone? Does it help coaches make better decisions, reduce avoidable overload and identify useful interventions? If a domain adds nothing, it should be removed. If the index works in Chennai but not in Delhi or Kodaikanal, the model must be revised.")
w("")
w("KEY: AEI becomes a validated index only by passing each research phase in order. Until then, report the domains separately, with their confidence.")
w("")
w("COACH: Coaches can contribute from day one. Every standardised test, logged session, environmental note and reasoned override on an AEI card becomes part of the evidence base that will validate or correct the index.")
w("")
w("CHECK: What data could your group collect this season, with the tools you already have, that would help move the AEI from Phase 1 to Phase 2?")
w("")

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content", "09_part17_toolkit.md")
open(path, "w").write("\n".join(L) + "\n")
print("wrote", path, len(" ".join(L).split()), "words")
